apiVersion: v1
kind: Secret
metadata: 
  namespace: three-tier
  name: mongo-sec
type: Opaque
data:  
  username: eWFzc2luZQ==  # Base64 encoded "yassine"
  password: eWFzc2luZTEyMw==  # Base64 encoded "yassine123"
