apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: three-tier
  labels:
    role: api
    env: demo
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: api
  template:
    metadata:
      labels:
        role: api
    spec:
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: api
        image: 443370706049.dkr.ecr.us-east-1.amazonaws.com/backend:28
        imagePullPolicy: Always
        env:
          - name: MONGO_URI
            value: "mongodb+srv://yassine:yassine123@prepai.cggcy.mongodb.net/?retryWrites=true&w=majority&appName=prepai"
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 2
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
        startupProbe:
          httpGet:
            path: /started
            port: 5000
          initialDelaySeconds: 0
          periodSeconds: 10
          failureThreshold: 30
