apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: three-tier
spec:
  selector:
    role: frontend
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
  type: ClusterIP
